name: Go
on:
  push:
    tags:
    - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '0'

    - name: Generate Git log
      run: |
        git fetch origin +refs/tags/*:refs/tags/*
        echo "Current Tag: ${GITHUB_REF}"
        git checkout ${GITHUB_REF} -b compile
        GITVER=$(git describe --tags)
        PREVVER=$(git describe --tags --abbrev=0 ${GITVER}~1)
        git log --oneline ${PREVVER}..${GITVER} > gittaglogs.txt

    - name: Get dependencies
      run: |
        go get -v -u github.com/shuLhan/go-bindata/...
        go get -v -t -d ./...

    - name: Build
      run: |
        #bash scripts/ci_release.sh windows amd64
        #bash scripts/ci_release.sh windows 386
        bash scripts/ci_release.sh linux amd64
        bash scripts/ci_release.sh linux 386
        bash scripts/ci_release.sh linux arm64
        # bash scripts/ci_release.sh linux arm
        # bash scripts/ci_release.sh linux mipsle
        # bash scripts/ci_release.sh linux mips
        # bash scripts/ci_release.sh darwin amd64
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          #scripts/build/cloud-torrent_windows_amd64.exe.gz
          #scripts/build/cloud-torrent_windows_386.exe.gz
          scripts/build/cloud-torrent_linux_amd64.gz
          scripts/build/cloud-torrent_linux_386.gz
          scripts/build/cloud-torrent_linux_arm64.gz
          # scripts/build/cloud-torrent_linux_arm_armv5.gz
          # scripts/build/cloud-torrent_linux_arm_armv6.gz
          # scripts/build/cloud-torrent_linux_arm_armv7.gz
          # scripts/build/cloud-torrent_linux_mipsle.gz
          # scripts/build/cloud-torrent_linux_mips.gz
          # scripts/build/cloud-torrent_darwin_amd64.gz
        prerelease: false
        draft: false
        body_path: gittaglogs.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

